version: '3'

services:
  jira:
    container_name: jira
    image: atlassian/jira-software:latest
    environment:
      - ATL_PROXY_NAME=jira.internal
      - ATL_PROXY_PORT=80
      - ATL_TOMCAT_SCHEME=http
    depends_on:
      - postgres


  confluence:
    container_name: confluence
    image: atlassian/confluence-server:latest
    environment:
      - ATL_PROXY_NAME=confluence.internal
      - ATL_PROXY_PORT=80
      - ATL_TOMCAT_SCHEME=http
    depends_on:
      - postgres


  bitbucket:
    container_name: bitbucket
    image: atlassian/bitbucket-server:latest
    environment:
      - SERVER_PROXY_NAME=bitbucket.internal
      - SERVER_PROXY_PORT=80
      - SERVER_SCHEME=http
    depends_on:
      - postgres


  postgres:
     build: ./database
     container_name: postgres
     ports:
      - 5432:5432
     environment:
      POSTGRES_DB: jira_db
      POSTGRES_USER: jira_admin
      POSTGRES_PASSWORD: JiraPassw0rd
     volumes:
      - postgres-data:/var/lib/postgresql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jira
      - confluence
      - bitbucket
      - postgres
    ports:
      - "80:80" #update this to your desired port
    networks:
      default:
        aliases:
          - jira.internal
          - confluence.internal
          - bitbucket.internal
          - postgres.internal

volumes:
  postgres-data:
    driver: local

# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' your_postgres_container_name  ==> in order to connect conflunce to postgres
# use the following to set up database on confluence 
      # POSTGRES_DB: jira_database
      # POSTGRES_USER: jira_user
      # POSTGRES_PASSWORD: jira_password
